language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - echo Hello World
deploy:
  api_key:
    secure: wpuDfDbQGBmFx6iTMGLFpNmxSHn6q0wkdlb7tZXkAWYyBfik9DDaTUxTpc/CxPj85tkj2Glot2BVuKQb+Mzt1ScdTZCUVzoj+dYwsc2qY/bcnWiCM1dceN644dAFjf9G+XsPbjAgrdfUSMJPjugDkRgn2aAR3at+b2QUFD8mmQuYGshdK0KYplG1UkRlOAbl1AE0YElVOWn5mkKyvA5NHRDyVDRN11hpo2k8Mpal+LaURBs7ulQZH6YrJc8JDwTsujmpqm113oW3FD/aRTAOjoiVv7z+RYwqZcA2B0zDf9r0W/upHhTBNYtvjPKnlolHwCVWyHym3X3HtmZ2pRezg7wh6jgbZtV6w9vX5ru/MRBcZIlOyFSNDrWIdkxg28Ml8mxwIONP1H24FHRd+2dGFLMllMcHevLAeJXoUA1n0pTZ76Ya8fXaoohoDIaKYSWLFUFSwTob2ft1t6i9TeP46i5gYKAS38AUUX8o/st8pWm2+CHaxKyinASW65lOba/gWEhpaa8yycLxjXDODNAAC76BBleLxEDQuM71zudqH7Kng06UUD6177wLGGHSkVCFrfJzeQclGCy96TJRz6TpXe1vSD3R+Lb2DQILsT5yYTMWkc7Rk/TJwPfdjSg/NnG5hRrr8tSSFVBNi8Sm7lS227zvYZzCIDXhUlxw8yOwz6M=
